language: node_js
node_js:
  - "8"
cache: yarn
branches:
  only:
    - master
before_script:
  - "yarn global add firebase-tools"
  - "yarn global add gatsby"
script:
  - "yarn test"
  - "yarn build"
after_success:
  - "firebase deploy --token=${KEY}"
